### ISSUE TITLE
Finish move from GitLab

### ISSUE THREAD

**Issue by thumbnail** [delta-leonis/zosma#3]
- [ ] Documentation has to be updated and moved to the wiki
 - [x] `CONTRIBUTING.md` has to be updated
 - [x] `README.md` has to be updated
 - [x] `LICENSE` has to be updated
 - [x] `.gitlab-ci.yml` has to be removed
 - [x] codacy configuration should be tweaked to better reflect intended code style.
 - [x] Move code from `ssh` package to another **new package name TBD**

**optional**
 - [ ] `.circleci/config.yml` might be updated to include test-reports

other references to GitLab have to be added to this issue and should be updated or removed as well.

**Comment by romni** [comment]
i fixed part of these issues in f9a62a7 and am currently working on porting the wiki. how will we settle the issues of which codacy rules to pick, and the root package name to use?

**Comment by thumbnail** [comment]
I think we can decide on a name for the root package name on slack for now together with @RyanMeulenkamp and @ThomasHakkers. Might need to change the organisation name as well.

The codacy rules are basically rules for PMD and checkstyles and need to be modeled after [the google style guilde](https://google.github.io/styleguide/javaguide.html). Probably the config for PMD and checkstyles are available online.
